version: '3.9'
services:
  cdmo:
    build:
      context: .
      dockerfile: Dockerfile  # Make sure your Dockerfile is named 'Dockerfile' and located in the same directory
    image: MatteoFasulo/multiple-couriers-planning
    volumes:
      - ./res:/src/res
    container_name: cvrp_project
    network_mode: "host"
